In [1]:
import pandas as pd
import glob
import os

In [2]:
data_folder = "data/"
data_files = glob.glob(os.path.join(data_folder, "*.csv"))

In [3]:
data_files

['data/turnstile_170722.csv',
 'data/turnstile_170520.csv',
 'data/turnstile_180407.csv',
 'data/turnstile_170325.csv',
 'data/turnstile_171007.csv',
 'data/turnstile_180203.csv',
 'data/turnstile_180217.csv',
 'data/turnstile_170318.csv',
 'data/turnstile_170708.csv',
 'data/turnstile_180428.csv',
 'data/turnstile_180414.csv',
 'data/turnstile_180616.csv',
 'data/turnstile_180602.csv',
 'data/turnstile_180825.csv',
 'data/turnstile_181124.csv',
 'data/turnstile_170527.csv',
 'data/turnstile_180818.csv',
 'data/turnstile_170902.csv',
 'data/turnstile_170916.csv',
 'data/turnstile_170121.csv',
 'data/turnstile_171202.csv',
 'data/turnstile_171216.csv',
 'data/turnstile_180210.csv',
 'data/turnstile_171028.csv',
 'data/turnstile_171014.csv',
 'data/turnstile_180303.csv',
 'data/turnstile_180317.csv',
 'data/turnstile_170225.csv',
 'data/turnstile_180707.csv',
 'data/turnstile_180908.csv',
 'data/turnstile_180505.csv',
 'data/turnstile_170812.csv',
 'data/turnstile_170422.csv',
 'data/turnstile_170218.csv',
 'data/turnstile_181222.csv',
 'data/turnstile_181020.csv',
 'data/turnstile_190105.csv',
 'data/turnstile_181208.csv',
 'data/turnstile_171104.csv',
 'data/turnstile_170408.csv',
 'data/turnstile_180512.csv',
 'data/turnstile_170805.csv',
 'data/turnstile_180922.csv',
 'data/turnstile_171111.csv',
 'data/turnstile_181027.csv',
 'data/turnstile_180113.csv',
 'data/turnstile_180714.csv',
 'data/turnstile_180728.csv',
 'data/turnstile_180106.csv',
 'data/turnstile_180310.csv',
 'data/turnstile_170624.csv',
 'data/turnstile_180120.csv',
 'data/turnstile_170204.csv',
 'data/turnstile_180929.csv',
 'data/turnstile_180915.csv',
 'data/turnstile_180901.csv',
 'data/turnstile_180519.csv',
 'data/turnstile_170826.csv',
 'data/turnstile_170211.csv',
 'data/turnstile_181229.csv',
 'data/turnstile_181215.csv',
 'data/turnstile_181201.csv',
 'data/turnstile_171125.csv',
 'data/turnstile_170401.csv',
 'data/turnstile_170415.csv',
 'data/turnstile_170429.csv',
 'data/turnstile_170603.csv',
 'data/turnstile_170617.csv',
 'data/turnstile_170819.csv',
 'data/turnstile_180526.csv',
 'data/turnstile_171118.csv',
 'data/turnstile_181006.csv',
 'data/turnstile_180324.csv',
 'data/turnstile_180721.csv',
 'data/turnstile_180127.csv',
 'data/turnstile_180331.csv',
 'data/turnstile_181013.csv',
 'data/turnstile_170610.csv',
 'data/turnstile_170930.csv',
 'data/turnstile_181117.csv',
 'data/turnstile_181103.csv',
 'data/turnstile_180630.csv',
 'data/turnstile_170304.csv',
 'data/turnstile_171230.csv',
 'data/turnstile_170107.csv',
 'data/turnstile_170311.csv',
 'data/turnstile_170729.csv',
 'data/turnstile_170701.csv',
 'data/turnstile_170715.csv',
 'data/turnstile_180421.csv',
 'data/turnstile_180623.csv',
 'data/turnstile_180804.csv',
 'data/turnstile_170513.csv',
 'data/turnstile_171209.csv',
 'data/turnstile_181110.csv',
 'data/turnstile_170506.csv',
 'data/turnstile_180811.csv',
 'data/turnstile_170923.csv',
 'data/turnstile_170909.csv',
 'data/turnstile_180224.csv',
 'data/turnstile_170128.csv',
 'data/turnstile_170114.csv',
 'data/turnstile_171223.csv',
 'data/turnstile_171021.csv',
 'data/turnstile_180609.csv']

In [4]:
df = pd.concat((pd.read_csv(f) for f in data_files))

In [5]:
df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,07/15/2017,00:00:00,REGULAR,6255579,2118659
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,07/15/2017,04:00:00,REGULAR,6255618,2118667
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,07/15/2017,08:00:00,REGULAR,6255632,2118689
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,07/15/2017,12:00:00,REGULAR,6255706,2118757
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,07/15/2017,16:00:00,REGULAR,6255875,2118806

In [6]:
df.sort_values(by = 'TIME')

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,07/15/2017,00:00:00,REGULAR,6255579,2118659
29027,G009,R151,02-00-05,CONEY IS-STILLW,DFNQ,BMT,12/03/2018,00:00:00,REGULAR,238721,184068
29033,G009,R151,02-00-05,CONEY IS-STILLW,DFNQ,BMT,12/04/2018,00:00:00,REGULAR,241798,186208
29039,G009,R151,02-00-05,CONEY IS-STILLW,DFNQ,BMT,12/05/2018,00:00:00,REGULAR,244903,188429
29045,G009,R151,02-00-05,CONEY IS-STILLW,DFNQ,BMT,12/06/2018,00:00:00,REGULAR,248055,190688
29051,G009,R151,02-00-05,CONEY IS-STILLW,DFNQ,BMT,12/07/2018,00:00:00,REGULAR,251139,192998
29057,G009,R151,02-05-00,CONEY IS-STILLW,DFNQ,BMT,12/01/2018,00:00:00,REGULAR,2246,0
29063,G009,R151,02-05-00,CONEY IS-STILLW,DFNQ,BMT,12/02/2018,00:00:00,REGULAR,2246,0
29069,G009,R151,02-05-00,CONEY IS-STILLW,DFNQ,BMT,12/03/2018,00:00:00,REGULAR,2246,0
29021,G009,R151,02-00-05,CONEY IS-STILLW,DFNQ,BMT,12/02/2018,00:00:00,REGULAR,237337,182872
29075,G009,R151,02-05-00,CONEY IS-STILLW,DFNQ,BMT,12/04/2018,00:00:00,REGULAR,2246,0
29087,G009,R151,02-05-00,CONEY IS-STILLW,DFNQ,BMT,12/06/2018,00:00:00,REGULAR,2246,0
29093,G009,R151,02-05-00,CONEY IS-STILLW,DFNQ,BMT,12/07/2018,00:00:00,REGULAR,2246,0
29099,G009,R151,02-05-01,CONEY IS-STILLW,DFNQ,BMT,12/01/2018,00:00:00,REGULAR,2,234
29105,G009,R151,02-05-01,CONEY IS-STILLW,DFNQ,BMT,12/02/2018,00:00:00,REGULAR,2,234
29111,G009,R151,02-05-01,CONEY IS-STILLW,DFNQ,BMT,12/03/2018,00:00:00,REGULAR,2,234
29117,G009,R151,02-05-01,CONEY IS-STILLW,DFNQ,BMT,12/04/2018,00:00:00,REGULAR,2,234
29123,G009,R151,02-05-01,CONEY IS-STILLW,DFNQ,BMT,12/05/2018,00:00:00,REGULAR,2,234
29129,G009,R151,02-05-01,CONEY IS-STILLW,DFNQ,BMT,12/06/2018,00:00:00,REGULAR,2,234
29081,G009,R151,02-05-00,CONEY IS-STILLW,DFNQ,BMT,12/05/2018,00:00:00,REGULAR,2246,0
29135,G009,R151,02-05-01,CONEY IS-STILLW,DFNQ,BMT,12/07/2018,00:00:00,REGULAR,2,234
29015,G009,R151,02-00-05,CONEY IS-STILLW,DFNQ,BMT,12/01/2018,00:00:00,REGULAR,235699,181419
29003,G009,R151,02-00-04,CONEY IS-STILLW,DFNQ,BMT,12/06/2018,00:00:00,REGULAR,7280762,10365093
28895,G009,R151,02-00-02,CONEY IS-STILLW,DFNQ,BMT,12/02/2018,00:00:00,REGULAR,576847,671670
28901,G009,R151,02-00-02,CONEY IS-STILLW,DFNQ,BMT,12/03/2018,00:00:00,REGULAR,577089,671937
28907,G009,R151,02-00-02,CONEY IS-STILLW,DFNQ,BMT,12/04/2018,00:00:00,REGULAR,577798,672837
28913,G009,R151,02-00-02,CONEY IS-STILLW,DFNQ,BMT,12/05/2018,00:00:00,REGULAR,578543,673731
28919,G009,R151,02-00-02,CONEY IS-STILLW,DFNQ,BMT,12/06/2018,00:00:00,REGULAR,579254,674638
28925,G009,R151,02-00-02,CONEY IS-STILLW,DFNQ,BMT,12/07/2018,00:00:00,REGULAR,580002,675554
28931,G009,R151,02-00-03,CONEY IS-STILLW,DFNQ,BMT,12/01/2018,00:00:00,REGULAR,173080,252392
...,...,...,...,...,...,...,...,...,...,...,...
118177,PTH16,R550,01-01-04,LACKAWANNA,1,PTH,11/15/2017,23:59:58,REGULAR,100088,51151
111988,PTH03,R552,00-02-01,JOURNAL SQUARE,1,PTH,01/28/2017,23:59:58,REGULAR,64342,78823
112022,PTH04,R551,00-04-05,GROVE STREET,1,PTH,07/16/2018,23:59:58,REGULAR,6178,2551
110128,PTH02,R544,00-00-01,HARRISON,1,PTH,06/23/2017,23:59:58,REGULAR,396573,27394
117560,PTH16,R550,01-01-04,LACKAWANNA,1,PTH,11/22/2017,23:59:58,REGULAR,104724,53088
117461,PTH16,R550,01-01-04,LACKAWANNA,1,PTH,11/29/2017,23:59:58,REGULAR,108576,54404
115831,PTH12,R542,00-00-04,TWENTY THIRD ST,1,PTH,01/20/2017,23:59:58,REGULAR,1618301,146678
113064,PTH03,R552,00-02-01,JOURNAL SQUARE,1,PTH,02/18/2017,23:59:58,REGULAR,68848,84342
119015,PTH17,R541,01-00-04,THIRTY THIRD ST,1,PTH,10/30/2018,23:59:58,REGULAR,104566,179116
114333,PTH06,R546,00-00-0A,PAVONIA/NEWPORT,1,PTH,05/31/2018,23:59:58,REGULAR,271735,207641
114523,PTH06,R546,00-00-0A,PAVONIA/NEWPORT,1,PTH,06/07/2018,23:59:58,REGULAR,278004,208177
112105,PTH03,R552,00-02-01,JOURNAL SQUARE,1,PTH,02/25/2017,23:59:58,REGULAR,70819,85928
122497,PTH20,R549,03-01-02,NEWARK HM HE,1,PTH,11/04/2018,23:59:58,REGULAR,118561,1111001
112897,PTH05,R543,00-00-06,EXCHANGE PLACE,1,PTH,03/22/2017,23:59:58,REGULAR,32953,337479
112683,PTH03,R552,00-02-01,JOURNAL SQUARE,1,PTH,02/04/2017,23:59:58,REGULAR,65831,80704
112310,PTH03,R552,00-02-01,JOURNAL SQUARE,1,PTH,02/11/2017,23:59:58,REGULAR,67247,82640
115373,PTH05,R543,00-01-02,EXCHANGE PLACE,1,PTH,12/17/2018,23:59:59,REGULAR,97183,262297
113472,PTH04,R551,00-04-00,GROVE STREET,1,PTH,11/01/2018,23:59:59,REGULAR,167241,198592
113967,PTH04,R551,00-01-00,GROVE STREET,1,PTH,08/15/2017,23:59:59,REGULAR,151241,73195
111803,PTH03,R552,00-00-08,JOURNAL SQUARE,1,PTH,02/12/2017,23:59:59,REGULAR,1216003,716065
116021,PTH09,R548,00-00-03,CHRISTOPHER ST,1,PTH,08/06/2018,23:59:59,REGULAR,150326,117030
115586,PTH11,R545,00-04-01,14TH STREET,1,PTH,07/18/2017,23:59:59,REGULAR,40730,575899
120645,PTH17,R541,01-00-05,THIRTY THIRD ST,1,PTH,01/25/2018,23:59:59,REGULAR,2501953,1630788
115247,PTH07,R550,00-00-00,CITY / BUS,1,PTH,08/27/2017,23:59:59,REGULAR,200682,162118
117861,PTH17,R541,01-00-0A,THIRTY THIRD ST,1,PTH,05/09/2017,23:59:59,REGULAR,589717,420219
116988,PTH05,R543,00-01-00,EXCHANGE PLACE,1,PTH,04/11/2017,23:59:59,REGULAR,33651,88574
118049,PTH17,R541,01-00-07,THIRTY THIRD ST,1,PTH,03/08/2017,23:59:59,REGULAR,28707,36147
113049,PTH05,R543,00-01-00,EXCHANGE PLACE,1,PTH,04/18/2017,23:59:59,REGULAR,36008,95080
115644,PTH11,R545,00-00-02,14TH STREET,1,PTH,06/14/2018,23:59:59,REGULAR,1255183,34018
114040,PTH07,R550,00-00-00,CITY / BUS,1,PTH,09/03/2017,23:59:59,REGULAR,204090,165012

In [15]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20766011 entries, 0 to 196742
Data columns (total 11 columns):
C/A                                                                     object
UNIT                                                                    object
SCP                                                                     object
STATION                                                                 object
LINENAME                                                                object
DIVISION                                                                object
DATE                                                                    object
TIME                                                                    object
DESC                                                                    object
ENTRIES                                                                 int64
EXITS                                                                   int64
dtypes: int64(2), object(9)
memory usage: 11.6 GB

In [16]:
df.info

20766011