In [1]:
import pandas as pd
import glob
import os

In [2]:
data_folder = "data/"
data_files = glob.glob(os.path.join(data_folder, "*.csv"))

In [9]:
data_files;

In [4]:
df = pd.concat((pd.read_csv(f) for f in data_files))

In [5]:
df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,07/15/2017,00:00:00,REGULAR,6255579,2118659
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,07/15/2017,04:00:00,REGULAR,6255618,2118667
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,07/15/2017,08:00:00,REGULAR,6255632,2118689
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,07/15/2017,12:00:00,REGULAR,6255706,2118757
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,07/15/2017,16:00:00,REGULAR,6255875,2118806

In [11]:
df.sort_values(by = 'UNIT')

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
124346,R101,R001,02-00-00,SOUTH FERRY,1RW,IRT,08/12/2017,01:00:00,REGULAR,2576508,4505692
10830,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/05/2018,21:00:00,REGULAR,447080,631455
10831,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/06/2018,01:00:00,REGULAR,447141,631571
10832,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/06/2018,05:00:00,REGULAR,447148,631601
10833,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/06/2018,09:00:00,REGULAR,447164,631640
10834,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/06/2018,13:00:00,REGULAR,447263,631886
10835,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/06/2018,17:00:00,REGULAR,447412,632072
10836,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/06/2018,21:00:00,REGULAR,447521,632231
10837,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/07/2018,01:00:00,REGULAR,447553,632287
10838,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/07/2018,05:00:00,REGULAR,447556,632301
10839,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/07/2018,09:00:00,REGULAR,447715,633040
10840,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/07/2018,13:00:00,REGULAR,447863,633956
10841,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/07/2018,17:00:00,REGULAR,448299,634326
10842,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/07/2018,21:00:00,REGULAR,449183,634587
10843,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/08/2018,01:00:00,REGULAR,449227,634662
10829,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/05/2018,17:00:00,REGULAR,446782,631231
10844,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/08/2018,05:00:00,REGULAR,449233,634673
10846,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/08/2018,13:00:00,REGULAR,449570,636389
10847,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/08/2018,17:00:00,REGULAR,450049,636768
10848,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/08/2018,21:00:00,REGULAR,450954,637068
10849,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/09/2018,01:00:00,REGULAR,451018,637159
10850,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/09/2018,05:00:00,REGULAR,451027,637176
10851,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/09/2018,09:00:00,REGULAR,451191,637959
10852,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/09/2018,13:00:00,REGULAR,451374,638855
10853,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/09/2018,17:00:00,REGULAR,451871,639246
10854,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/09/2018,21:00:00,REGULAR,452756,639547
10855,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/10/2018,01:00:00,REGULAR,452816,639617
10856,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/10/2018,05:00:00,REGULAR,452825,639639
10857,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/10/2018,09:00:00,REGULAR,453000,640356
10858,A060,R001,00-00-06,WHITEHALL S-FRY,R1W,BMT,05/10/2018,13:00:00,REGULAR,453194,641257
...,...,...,...,...,...,...,...,...,...,...,...
110409,N702A,R572,01-03-01,96 ST-2 AVE,Q,IND,12/03/2017,16:00:00,REGULAR,98538,137959
110267,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/08/2017,00:00:00,REGULAR,199666,169494
110265,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/07/2017,16:00:00,REGULAR,199437,169101
110240,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/03/2017,12:00:00,REGULAR,196395,166823
110241,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/03/2017,16:00:00,REGULAR,196541,166934
110242,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/03/2017,20:00:00,REGULAR,196635,167048
110243,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/04/2017,00:00:00,REGULAR,196658,167096
110244,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/04/2017,04:00:00,REGULAR,196659,167100
110245,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/04/2017,08:00:00,REGULAR,196728,167148
110246,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/04/2017,12:00:00,REGULAR,196870,167212
110247,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/04/2017,16:00:00,REGULAR,196954,167258
110248,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/04/2017,20:00:00,REGULAR,197126,167567
110249,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/05/2017,00:00:00,REGULAR,197160,167650
110250,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/05/2017,04:00:00,REGULAR,197161,167662
110251,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/05/2017,08:00:00,REGULAR,197279,167718
110252,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/05/2017,12:00:00,REGULAR,197659,167791
110253,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/05/2017,16:00:00,REGULAR,197762,167862
110254,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/05/2017,20:00:00,REGULAR,197943,168149
110255,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/06/2017,00:00:00,REGULAR,197979,168254
110256,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/06/2017,04:00:00,REGULAR,197982,168258
110257,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/06/2017,08:00:00,REGULAR,198087,168331
110258,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/06/2017,12:00:00,REGULAR,198468,168411
110259,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/06/2017,16:00:00,REGULAR,198587,168483
110260,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/06/2017,20:00:00,REGULAR,198782,168769
110261,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/07/2017,00:00:00,REGULAR,198820,168872
110262,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/07/2017,04:00:00,REGULAR,198821,168879
110263,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/07/2017,08:00:00,REGULAR,198920,168934
110264,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/07/2017,12:00:00,REGULAR,199313,169006
110266,N702A,R572,01-00-02,96 ST-2 AVE,Q,IND,12/07/2017,20:00:00,REGULAR,199627,169376
109468,N702A,R572,01-00-03,96 ST-2 AVE,Q,IND,03/06/2017,20:00:00,REGULAR,21450,24651

In [7]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20766011 entries, 0 to 196742
Data columns (total 11 columns):
C/A                                                                     object
UNIT                                                                    object
SCP                                                                     object
STATION                                                                 object
LINENAME                                                                object
DIVISION                                                                object
DATE                                                                    object
TIME                                                                    object
DESC                                                                    object
ENTRIES                                                                 int64
EXITS                                                                   int64
dtypes: int64(2), object(9)
memory usage: 11.6 GB

In [10]:
df.info

<bound method DataFrame.info of           C/A  UNIT       SCP        STATION LINENAME DIVISION        DATE  \
0        A002  R051  02-00-00          59 ST  NQR456W      BMT  07/15/2017
1        A002  R051  02-00-00          59 ST  NQR456W      BMT  07/15/2017
2        A002  R051  02-00-00          59 ST  NQR456W      BMT  07/15/2017
3        A002  R051  02-00-00          59 ST  NQR456W      BMT  07/15/2017
4        A002  R051  02-00-00          59 ST  NQR456W      BMT  07/15/2017
5        A002  R051  02-00-00          59 ST  NQR456W      BMT  07/15/2017
6        A002  R051  02-00-00          59 ST  NQR456W      BMT  07/16/2017
7        A002  R051  02-00-00          59 ST  NQR456W      BMT  07/16/2017
8        A002  R051  02-00-00          59 ST  NQR456W      BMT  07/16/2017
9        A002  R051  02-00-00          59 ST  NQR456W      BMT  07/16/2017
10       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/16/2017
11       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/16/2017
12       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/17/2017
13       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/17/2017
14       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/17/2017
15       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/17/2017
16       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/17/2017
17       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/17/2017
18       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/18/2017
19       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/18/2017
20       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/18/2017
21       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/18/2017
22       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/18/2017
23       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/18/2017
24       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/19/2017
25       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/19/2017
26       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/19/2017
27       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/19/2017
28       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/19/2017
29       A002  R051  02-00-00          59 ST  NQR456W      BMT  07/19/2017
...       ...   ...       ...            ...      ...      ...         ...
196713  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/04/2018
196714  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/04/2018
196715  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/04/2018
196716  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/04/2018
196717  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/04/2018
196718  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/04/2018
196719  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/05/2018
196720  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/05/2018
196721  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/05/2018
196722  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/05/2018
196723  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/05/2018
196724  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/05/2018
196725  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/06/2018
196726  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/06/2018
196727  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/06/2018
196728  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/06/2018
196729  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/06/2018
196730  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/06/2018
196731  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/07/2018
196732  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/07/2018
196733  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/07/2018
196734  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/07/2018
196735  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/07/2018
196736  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/07/2018
196737  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/08/2018
196738  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/08/2018
196739  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/08/2018
196740  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/08/2018
196741  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/08/2018
196742  TRAM2  R469  00-03-01  RIT-ROOSEVELT        R      RIT  06/08/2018

            TIME     DESC  ENTRIES  \
0       00:00:00  REGULAR  6255579
1       04:00:00  REGULAR  6255618
2       08:00:00  REGULAR  6255632
3       12:00:00  REGULAR  6255706
4       16:00:00  REGULAR  6255875
5       20:00:00  REGULAR  6256108
6       00:00:00  REGULAR  6256246
7       04:00:00  REGULAR  6256266
8       08:00:00  REGULAR  6256277
9       12:00:00  REGULAR  6256325
10      16:00:00  REGULAR  6256479
11      20:00:00  REGULAR  6256674
12      00:00:00  REGULAR  6256764
13      04:00:00  REGULAR  6256776
14      08:00:00  REGULAR  6256810
15      12:00:00  REGULAR  6256963
16      16:00:00  REGULAR  6257204
17      20:00:00  REGULAR  6257970
18      00:00:00  REGULAR  6258171
19      04:00:00  REGULAR  6258202
20      08:00:00  REGULAR  6258243
21      12:00:00  REGULAR  6258370
22      16:00:00  REGULAR  6258656
23      20:00:00  REGULAR  6259369
24      00:00:00  REGULAR  6259618
25      04:00:00  REGULAR  6259655
26      08:00:00  REGULAR  6259689
27      12:00:00  REGULAR  6259818
28      16:00:00  REGULAR  6260107
29      20:00:00  REGULAR  6260322
...          ...      ...      ...
196713  01:00:00  REGULAR  2912436
196714  05:00:00  REGULAR  2912438
196715  09:00:00  REGULAR  2912797
196716  13:00:00  REGULAR  2913210
196717  17:00:00  REGULAR  2913697
196718  21:00:00  REGULAR  2914165
196719  01:00:00  REGULAR  2914327
196720  05:00:00  REGULAR  2914334
196721  09:00:00  REGULAR  2914787
196722  13:00:00  REGULAR  2915100
196723  17:00:00  REGULAR  2915495
196724  21:00:00  REGULAR  2915949
196725  01:00:00  REGULAR  2916117
196726  05:00:00  REGULAR  2916120
196727  09:00:00  REGULAR  2916441
196728  13:00:00  REGULAR  2916828
196729  17:00:00  REGULAR  2917268
196730  21:00:00  REGULAR  2917618
196731  01:00:00  REGULAR  2917765
196732  05:00:00  REGULAR  2917768
196733  09:00:00  REGULAR  2918078
196734  13:00:00  REGULAR  2918513
196735  17:00:00  REGULAR  2918965
196736  21:00:00  REGULAR  2919376
196737  01:00:00  REGULAR  2919541
196738  05:00:00  REGULAR  2919546
196739  09:00:00  REGULAR  2919876
196740  13:00:00  REGULAR  2920314
196741  17:00:00  REGULAR  2920790
196742  21:00:00  REGULAR  2921165

        EXITS
0                                                 2118659
1                                                 2118667
2                                                 2118689
3                                                 2118757
4                                                 2118806
5                                                 2118841
6                                                 2118858
7                                                 2118863
8                                                 2118878
9                                                 2118925
10                                                2118966
11                                                2119000
12                                                2119017
13                                                2119018
14                                                2119129
15                                                2119393
16                                                2119444
17                                                2119525
18                                                2119550
19                                                2119553
20                                                2119650
21                                                2119928
22                                                2120008
23                                                2120089
24                                                2120128
25                                                2120130
26                                                2120219
27                                                2120491
28                                                2120554
29                                                2120628
...                                                   ...
196713                                             386964
196714                                             386964
196715                                             386967
196716                                             386968
196717                                             386971
196718                                             386978
196719                                             386982
196720                                             386983
196721                                             386985
196722                                             386990
196723                                             386997
196724                                             387000
196725                                             387005
196726                                             387005
196727                                             387007
196728                                             387013
196729                                             387019
196730                                             387019
196731                                             387022
196732                                             387022
196733                                             387026
196734                                             387029
196735                                             387034
196736                                             387037
196737                                             387038
196738                                             387039
196739                                             387048
196740                                             387055
196741                                             387062
196742                                             387069

[20766011 rows x 11 columns]>

In [3]:
df_2018 = pd.read_pickle('./data/2018_mta_data_diffs')

In [4]:
df_2018

                               Unnamed: 0     ENTRIES  \
STATION   DATE       TIME
1 AV      01/01/2018 03:00:00      307615  3042947337
                     07:00:00      307625  3042947783
                     11:00:00      307635  3042948650
                     15:00:00      307645  3042951071
                     19:00:00      307655  3042953851
                     23:00:00      307665  3042955764
          01/01/2019 03:00:00   103361460  3041094366
                     07:00:00   103361470  3041094797
                     11:00:00   103361480  3041095642
                     15:00:00   103361490  3041097952
                     19:00:00   103361500  3041100841
                     23:00:00   103361510  3041102742
          01/02/2018 03:00:00      307675  3042956363
                     07:00:00      307685  3042956819
                     11:00:00      307695  3042961508
                     15:00:00      307705  3042964925
                     19:00:00      307715  3042971928
                     23:00:00      307725  3042975031
          01/02/2019 03:00:00   103361520  3041103233
                     07:00:00   103361530  3041103591
                     11:00:00   103361540  3041107950
                     15:00:00   103361550  3041111287
                     19:00:00   103361560  3041118032
                     23:00:00   103361570  3041121218
          01/03/2018 03:00:00      307735  3042975878
                     07:00:00      307745  3042976414
                     11:00:00      307755  3042981489
                     15:00:00      307765  3042985038
                     19:00:00      307775  3042992446
                     23:00:00      307785  3042996295
...                                   ...         ...
ZEREGA AV 12/29/2018 00:00:00    62895189     1546299
                     04:00:00    62895195     1546326
                     08:00:00    62895201     1546559
                     12:00:00    62895207     1546899
                     16:00:00    62895213     1547309
                     20:00:00    62895219     1547604
          12/30/2017 00:00:00     1059705    54400372
                     04:00:00     1059711    54400394
                     08:00:00     1059717    54400575
                     12:00:00     1059723    54400864
                     16:00:00     1059729    54401181
                     20:00:00     1059735    54401378
          12/30/2018 00:00:00    62895225     1547697
                     04:00:00    62895231     1547717
                     08:00:00    62895237     1547862
                     12:00:00    62895243     1548161
                     16:00:00    62895249     1548475
                     20:00:00    62895255     1548672
          12/31/2017 00:00:00     1059741    54401502
                     04:00:00     1059747    54401519
                     08:00:00     1059753    54401640
                     12:00:00     1059759    54401889
                     16:00:00     1059765    54402136
                     20:00:00     1059771    54402332
          12/31/2018 00:00:00    62895261     1548774
                     04:00:00    62895267     1548793
                     08:00:00    62895273     1549232
                     12:00:00    62895279     1549673
                     16:00:00    62895285     1550096
                     20:00:00    62895291     1550419

                               EXITS                                                                 \
STATION   DATE       TIME
1 AV      01/01/2018 03:00:00                                       1.642545e+09
                     07:00:00                                       1.642546e+09
                     11:00:00                                       1.642547e+09
                     15:00:00                                       1.642549e+09
                     19:00:00                                       1.642553e+09
                     23:00:00                                       1.642555e+09
          01/01/2019 03:00:00                                       1.629408e+09
                     07:00:00                                       1.629408e+09
                     11:00:00                                       1.629409e+09
                     15:00:00                                       1.629412e+09
                     19:00:00                                       1.629415e+09
                     23:00:00                                       1.629417e+09
          01/02/2018 03:00:00                                       1.642556e+09
                     07:00:00                                       1.642557e+09
                     11:00:00                                       1.642563e+09
                     15:00:00                                       1.642566e+09
                     19:00:00                                       1.642573e+09
                     23:00:00                                       1.642577e+09
          01/02/2019 03:00:00                                       1.629418e+09
                     07:00:00                                       1.629419e+09
                     11:00:00                                       1.629425e+09
                     15:00:00                                       1.629429e+09
                     19:00:00                                       1.629435e+09
                     23:00:00                                       1.629439e+09
          01/03/2018 03:00:00                                       1.642577e+09
                     07:00:00                                       1.642579e+09
                     11:00:00                                       1.642585e+09
                     15:00:00                                       1.642589e+09
                     19:00:00                                       1.642596e+09
                     23:00:00                                       1.642600e+09
...                                                                          ...
ZEREGA AV 12/29/2018 00:00:00                                       6.139460e+05
                     04:00:00                                       6.140580e+05
                     08:00:00                                       6.141660e+05
                     12:00:00                                       6.143520e+05
                     16:00:00                                       6.146010e+05
                     20:00:00                                       6.150050e+05
          12/30/2017 00:00:00                                       1.807159e+06
                     04:00:00                                       1.807263e+06
                     08:00:00                                       1.807348e+06
                     12:00:00                                       1.807509e+06
                     16:00:00                                       1.807722e+06
                     20:00:00                                       1.808064e+06
          12/30/2018 00:00:00                                       6.153280e+05
                     04:00:00                                       6.154450e+05
                     08:00:00                                       6.155130e+05
                     12:00:00                                       6.156710e+05
                     16:00:00                                       6.158820e+05
                     20:00:00                                       6.162020e+05
          12/31/2017 00:00:00                                       1.808331e+06
                     04:00:00                                       1.808424e+06
                     08:00:00                                       1.808482e+06
                     12:00:00                                       1.808626e+06
                     16:00:00                                       1.808810e+06
                     20:00:00                                       1.809053e+06
          12/31/2018 00:00:00                                       6.164250e+05
                     04:00:00                                       6.165160e+05
                     08:00:00                                       6.167390e+05
                     12:00:00                                       6.169770e+05
                     16:00:00                                       6.173460e+05
                     20:00:00                                       6.178310e+05

                               ENTRIES_DIFF  EXITS_DIFF
STATION   DATE       TIME
1 AV      01/01/2018 03:00:00          1838        2433
                     07:00:00           446         751
                     11:00:00           867        1094
                     15:00:00          2421        2327
                     19:00:00          2780        3459
                     23:00:00          1913        2293
          01/01/2019 03:00:00          1613        2121
                     07:00:00           431         755
                     11:00:00           845        1075
                     15:00:00          2310        2306
                     19:00:00          2889        3555
                     23:00:00          1901        2285
          01/02/2018 03:00:00           599         540
                     07:00:00           456        1283
                     11:00:00          4689        6095
                     15:00:00          3417        3535
                     19:00:00          7003        6373
                     23:00:00          3103        4042
          01/02/2019 03:00:00           491         430
                     07:00:00           358        1068
                     11:00:00          4359        6154
                     15:00:00          3337        3718
                     19:00:00          6745        6200
                     23:00:00          3186        3488
          01/03/2018 03:00:00           847         624
                     07:00:00           536        1406
                     11:00:00          5075        6598
                     15:00:00          3549        3636
                     19:00:00          7408        6437
                     23:00:00          3849        4280
...                                     ...         ...
ZEREGA AV 12/29/2018 00:00:00     -86103483   -35439809
                     04:00:00            27         112
                     08:00:00           233         108
                     12:00:00           340         186
                     16:00:00           410         249
                     20:00:00           295         404
          12/30/2017 00:00:00     -32350106   -32813802
                     04:00:00            22         104
                     08:00:00           181          85
                     12:00:00           289         161
                     16:00:00           317         213
                     20:00:00           197         342
          12/30/2018 00:00:00            93         323
                     04:00:00            20         117
                     08:00:00           145          68
                     12:00:00           299         158
                     16:00:00           314         211
                     20:00:00           197         320
          12/31/2017 00:00:00           124         267
                     04:00:00            17          93
                     08:00:00           121          58
                     12:00:00           249         144
                     16:00:00           247         184
                     20:00:00           196         243
          12/31/2018 00:00:00           102         223
                     04:00:00            19          91
                     08:00:00           439         223
                     12:00:00           441         238
                     16:00:00           423         369
                     20:00:00           323         485

[1564143 rows x 5 columns]